name: Docker Image CI
on:
  push:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read
    env:
      REGISTRY: ghcr.io
      USERNAME: ShanghaitechGeekPie
      IMAGE_NAME : ${{ github.repository }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ env.USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{github.ref == 'refs/heads/master' || github.ref == 'refs/heads/release'}}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
