name: Docker Image CI
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      tag: ${{ secrets.CI_REGISTRY }}/geekpie/coursebench-backend:latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.CI_REGISTRY }}
        username: ${{ secrets.CI_REGISTRY_USER }}
        password: ${{ secrets.CI_REGISTRY_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $tag
    - name: Push the Docker image1
      run: docker push $tag
